/**
 * Extracts the Open Sans woff2 subsets embedded in the design bundle into
 * web-admin/public/fonts/, and writes the matching @font-face stylesheet.
 * Only the subsets a Vietnamese app needs are kept: latin, latin-ext, vietnamese.
 */
const fs = require('fs');
const path = require('path');

const ROOT = 'd:/AgriXAI Farmer';
const SRC = path.join(ROOT, 'AgriXAI Farmer v4 - Standalone (1).html');
const OUT_DIR = path.join(ROOT, 'web-admin', 'public', 'fonts');
const CSS_OUT = path.join(ROOT, 'web-admin', 'src', 'app', 'fonts.css');

const html = fs.readFileSync(SRC, 'utf8');
function block(type) {
  const open = `<script type="__bundler/${type}">`;
  const i = html.indexOf(open);
  const j = html.indexOf('</script>', i + open.length);
  return html.slice(i + open.length, j).trim();
}
const manifest = JSON.parse(block('manifest'));
const template = JSON.parse(block('template'));

const KEEP = new Set(['latin', 'latin-ext', 'vietnamese']);
const WEIGHT_NAME = {
  400: 'Regular',
  500: 'Medium',
  600: 'SemiBold',
  700: 'Bold',
  800: 'ExtraBold',
};

// Each rule is preceded by a `/* subset */` comment in the bundled stylesheet.
const re =
  /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
const faces = [];
let m;
while ((m = re.exec(template)) !== null) {
  const subset = m[1];
  const body = m[2];
  const weight = Number(/font-weight:\s*(\d+)/.exec(body)?.[1]);
  const uuid = /src:\s*url\("([^"]+)"\)/.exec(body)?.[1];
  const range = /unicode-range:\s*([^;]+);/.exec(body)?.[1]?.trim();
  if (!KEEP.has(subset) || !uuid || !weight || !manifest[uuid]) continue;
  faces.push({subset, weight, uuid, range});
}

fs.mkdirSync(OUT_DIR, {recursive: true});
const lines = [
  '/**',
  ' * Open Sans - BUNDLED with the app, extracted from the design file',
  ' * "AgriXAI Farmer v4 - Standalone (1).html". Never fetched from Google Fonts',
  ' * at runtime (design rule 3.3).',
  ' *',
  ' * GENERATED by shared/design/extract-fonts.js - do not edit by hand.',
  ' */',
  '',
];

for (const f of faces) {
  const name = `OpenSans-${WEIGHT_NAME[f.weight]}-${f.subset}.woff2`;
  fs.writeFileSync(path.join(OUT_DIR, name), Buffer.from(manifest[f.uuid].data, 'base64'));
  lines.push('@font-face {');
  lines.push("  font-family: 'Open Sans';");
  lines.push('  font-style: normal;');
  lines.push(`  font-weight: ${f.weight};`);
  lines.push('  font-display: swap;');
  lines.push(`  src: url('/fonts/${name}') format('woff2');`);
  lines.push(`  unicode-range: ${f.range};`);
  lines.push('}');
  lines.push('');
}

fs.writeFileSync(CSS_OUT, lines.join('\n'), 'utf8');
console.log(`extracted ${faces.length} woff2 subsets -> web-admin/public/fonts/`);
const total = faces.reduce(
  (n, f) => n + fs.statSync(path.join(OUT_DIR, `OpenSans-${WEIGHT_NAME[f.weight]}-${f.subset}.woff2`)).size,
  0,
);
console.log(`total ${(total / 1024).toFixed(1)} KB`);
console.log('weights:', [...new Set(faces.map((f) => f.weight))].join(', '));
console.log('subsets:', [...new Set(faces.map((f) => f.subset))].join(', '));
